### ISSUE TITLE
After upgradingto v2+, browser cache from v1+ is not refreshed

### ISSUE THREAD

**Issue by tsimbalar** [continuousit/seq-releases#289]
After installing the latest beta (2.0.13-pre), when I open up Seq in my browser (both in IE11 and Firefox 38), the url http://localhost:5341/#/events opens ... but I see exactly the same display as before ... 
The version number showing in the bottom of the screen is still 1.5.17 on all tabs.

Only when I Ctrl+F5 do I get the fresh new stuff !

I suppose there is some browser-cache invalidation to do somewhere ! 

Not a big big issue, but it did frighten me a bit, thinking the install had failed !

**Comment by nblumhardt** [comment]
Thanks for the note - will check this out. Cheers!

**Comment by nblumhardt** [comment]
Fixed in Seq 3.1.

**Comment by nblumhardt** [comment]
Since the problem was an invalid cache attribute, the 3.1.x -> 3.1.y upgrade should be the first where this is sorted out.

**Comment by tsimbalar** [comment]
I still get the issue when I upgrade locally on my personal instance (last time, from v3.2.11-pre to v3.2.13-pre). The version number is invorrect until I hit Ctrl+F5 ... at least in Firefox which is my main browser.

(we also saw it in prod when upgrading from v2.x to 3.1x ... but I believe this is normal)

**Comment by nblumhardt** [comment]
Thanks for the update; I've been testing on Chrome each release, but sounds like I need to check Firefox too - I'll check it out.
